namespace HoDoKuNative.UI
{
    [default_interface]
    runtimeclass PuzzleMetadata
    {
        PuzzleMetadata();
        String PuzzleString{ get; set; };
        String SolutionString{ get; set; };
        StepDifficulty Level{ get; set; };
        Int32 GivenCount{ get; set; };
        Int32 TotalScore{ get; set; };
    }
}

