namespace HoDoKuNative.UI
{
    enum StepDifficulty
    {
        Easy,
        Medium,
        Hard,
        Unfair,
        Extreme
    };

    [default_interface]
    runtimeclass CandidateAction
    {
        CandidateAction(Int32 cell, Int32 digit);
        Int32 Cell{ get; };
        Int32 Digit{ get; };
    }

    [default_interface]
    runtimeclass SudokuStep
    {
        SudokuStep();
        String Name{ get; set; };
        String Explanation{ get; set; };
        StepDifficulty Difficulty{ get; set; };
        Int32 Score{ get; set; };

        IVector<CandidateAction> Eliminations{ get; };
        IVector<CandidateAction> Assignments{ get; };
    }
}

